### Get secret from local store
GET http://localhost:3509/v1.0/secrets/my-secret-store/my-secret

### Get secret from AWS Secrets Manager
GET http://localhost:3509/v1.0/secrets/awssecretmanager/dapr-demo

### Get secret from Azure Key Vault
GET http://localhost:3509/v1.0/secrets/azurekeyvault/dapr-demo
